/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Login & General
        primary: "#007BFF",
        "background-light": "#f5f7f8",
        "background-surface": "#F8F9FA",
        "background-soft": "#F8F9FA",
        "background-dark": "#0f1923",
        "primary-dashboard": "#0B5FFF",
        "primary-inventory": "#005A9C",
        "primary-profile": "#1664f3",
        "secondary-gray": "#6C757D",
        "text-dark": "#212529",
        "text-light": "#1F2937",
        "text-primary": "#1D2939",
        "text-secondary": "#667085",
        "background-dashboard": "#F9FAFB",
        "background-inventory": "#f5f6f8",
        "background-profile": "#f5f6f8",
        "background-dark": "#0f1623",
        "surface-light": "#FFFFFF",
        "surface-dark": "#1f2937",
        "border-light": "#E5E7EB",
        "border-dark": "#374151",
        warning: "#FFC107", // Updated to match design
        critical: "#D0021B",
        success: "#10B981",
        "card-bg-light": "#F0F2F5",
        "card-bg-dark": "#1a222f",
        error: "#EF4444",
        danger: "#DC3545",
        "primary-darker": "#004B81",
        "primary-po": "#4A90E2",
        "card-light": "#F9F9F9",
        "card-dark": "#1A2233",
        "text-primary-light": "#333333",
        "text-primary-dark": "#F0F0F0",
        "text-secondary-light": "#888888",
        "text-secondary-dark": "#A0A0A0",
        "border-light": "#EAEAEA",
        "border-dark": "#2D3748",
        // iOS Colors
        "ios-blue": "#007AFF",
        "ios-green": "#34C759",
        "ios-bg-white": "#FFFFFF",
        "ios-text-dark": "#1C1C1E",
        "ios-text-medium": "#8A8A8E",
        "ios-border-light": "#E5E5EA",
        "app-primary": "#005A9C",
        "app-secondary": "#6B7280",
        "neutral-light": "#F0F2F5",
        "neutral-dark": "#1C2431",
        "text-primary-light": "#1A1A1A",
        "text-primary-dark": "#F0F2F5",
        "text-secondary-light": "#6B7280",
        "text-secondary-dark": "#94A3B8",
        "text-main": "#343A40",
        "status-pending": "#F39C12",
        "status-approved": "#28a745",
        "status-rejected": "#dc3545",
        "action-approve": "#1E8449",
        "action-reject": "#E74C3C",
        "border-color": "#E0E0E0",
        "surface": "#ffffff",
        "on-surface": "#1C1B1F",
        "secondary-text": "#757575",
        "outline": "#cddbea",
        "error": "#B3261E",
        "text-heading": "#1C1B1F",
        "text-body": "#49454F",
        "on-surface-light": "#1a1c1e",
        "on-surface-dark": "#e2e2e6",
        "on-surface-variant-light": "#42474e",
        "on-surface-variant-dark": "#c2c7ce",
        "text-primary-light": "#1F2937",
        "text-primary-dark": "#f5f7f8",
        "text-secondary-light": "#6B7281",
        "text-secondary-dark": "#9ca3af",
        "border-light": "#cddbea",
        "border-dark": "#374151",
        "skeleton": "#e0e0e0",
        "dark-skeleton": "#333333",
        "surface-light": "#FFFFFF",
        "surface-dark": "#1E1E1E",
        "text-primary-light": "#1C1B1F",
        "text-primary-dark": "#E3E3E3",
        "text-secondary-light": "#49454F",
        "text-secondary-dark": "#C7C7C7",
        "on-surface-variant": "#49454F",
        "warning": "#ffc107",
        "secondary": "#6C757D",
        "error-container": "#F9DEDC",
        "on-error-container": "#410E0B",
        "scrim": "rgba(0, 0, 0, 0.4)",
        "surface-light": "#ffffff",
        "on-surface-light": "#1C1B1F",
        "on-surface-variant-light": "#49454F",
        "text-light": "#1D2A39",
        "text-dark": "#F0F2F5",
        "border-light": "#eaeaeB",
        "border-dark": "#3a3a3c",
        "placeholder-light": "#a1a1a1",
        "placeholder-dark": "#7e7e7e",
        "card-light": "#ffffff",
        "card-dark": "#1c1c1e",
        "surface-light": "#ffffff",
        "surface-dark": "#1f2937",
        "text-primary-light": "#111827",
        "text-primary-dark": "#f9fafb",
        "text-secondary-light": "#6b7280",
        "text-secondary-dark": "#9ca3af",
        "card-light": "#FFFFFF",
        "card-dark": "#1a2938",
        "border-light": "#E9ECEF",
        "border-dark": "#343a40",
        "primary-container-light": "#dce1ff",
        "on-primary-container-light": "#001a40",
        "secondary-container-light": "#e0e2ec",
        "on-secondary-container-light": "#191c2c",
        "on-surface-light": "#1a1c1a",
        "on-surface-dark": "#e2e3e0",
        "subtle-light": "#DEE2E6",
        "subtle-dark": "#343a40",
        "neutral-100": "#ffffff",
        "neutral-200": "#f8f9fa",
        "neutral-300": "#e9ecef",
        "neutral-400": "#d1d5db",
        "neutral-800": "#343a40",
        "neutral-900": "#1f2937",
        "card-light": "#FFFFFF",
        "card-dark": "#1a2632",
        "text-primary-light": "#333333",
        "text-primary-dark": "#E5E7EB",
        "text-secondary-light": "#888888",
        "text-secondary-dark": "#9CA3AF",
        "text-light-primary": "#1A1A1A",
        "text-dark-primary": "#f0f2f4",
        "text-light-secondary": "#6B7280",
        "text-dark-secondary": "#a0aec0",
        success: "#34C759",
        // Material Design 3 Colors
        "on-primary": "#ffffff",
        "primary-container": "#D6E3FF",
        "on-primary-container": "#001B3F",
        "on-surface": "#1C1B1F",
        "surface-variant": "#E1E2EC",
        "on-surface-variant": "#44474F",
        "outline-variant": "#C4C6D0",
        // Additional surface colors
        "surface-light": "#FFFFFF",
        "surface-dark": "#182431",
        "on-surface-light": "#1A1C1E",
        "on-surface-dark": "#E2E2E6",
        "outline-light": "#E0E2E6",
        "outline-dark": "#44474B",
        // Additional text colors
        "text-light": "#0f172a",
        "text-dark": "#e2e8f0",
        "text-secondary-light": "#64748b",
        "text-secondary-dark": "#94a3b8",
        // Debt Summary colors
        "text-primary": "#212529",
        "text-secondary": "#6C757D",
        surface: "#FFFFFF",
        "accent-debt": "#FFC107",
      },
      fontFamily: {
        // Google Fonts: Inter for body text (font-display, font-body)
        display: ["Inter_400Regular", "Inter_500Medium", "Inter_600SemiBold", "Inter_700Bold", "Inter", "sans-serif"],
        body: ["Inter_400Regular", "Inter_500Medium", "Inter_600SemiBold", "Inter_700Bold", "Inter", "sans-serif"],
        // Google Fonts: Poppins for headings (font-heading)
        heading: ["Poppins_700Bold", "Poppins", "sans-serif"],
      },
      letterSpacing: {
        tighter: -0.8,
        tight: -0.4,
        normal: 0,
        wide: 0.4,
        wider: 0.8,
        widest: 1.6,
        light: 0.2, // Custom mapping for 'tracking-light' to safe number
      },
      borderRadius: {
        DEFAULT: "12px",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        // Using simplified values that React Native/NativeWind can handle
        // Note: React Native doesn't support multiple shadows, so we use single shadow values
        soft: "0 4px 6px rgba(0, 0, 0, 0.05)",
        "soft-m3": "0 2px 4px rgba(0,0,0,0.08)", // Simplified from multiple shadows
        top: "0 -4px 6px rgba(0, 0, 0, 0.05)",
      },
    },
  },
  plugins: [],
};
